// <auto-generated />
namespace mallform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shopID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shopID));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201542095_shopID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
