// <auto-generated />
namespace mallform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class totalAmountInRent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(totalAmountInRent));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171031132_totalAmountInRent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
